version: '3.3'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zk1
    ports:
      - "2181:2181"
    hostname: zk1
    networks:
      - distributed-pbm
    tty: true

  kafka1:
    image: wurstmeister/kafka
    container_name: kafka1
    depends_on: [zookeeper]
    ports:
      - "9092:9092"
    links:
      - zookeeper
    hostname: kafka1
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "requests-data:6:3"

      KAFKA_LISTENERS: PLAINTEXT://:19092,PLAINTEXT_HOST://:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_BROKER_ID: 1
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka1:19092, PLAINTEXT_HOST://${DOCKER_HOST_IP:-127.0.0.1}:9092
    networks:
      - distributed-pbm
    tty: true

  kafka-connect:
    image: 'bitnami/kafka:2.5.0'
    container_name: kafka_connect
    ports:
      - '8079:8083'
    volumes:
      - './kafka_connect_data:/bitnami'
      - './kafka_connect_config/worker.properties:/opt/bitnami/kafka/config/worker.properties'
    depends_on:
      - zookeeper
      - kafka1
    networks:
      - distributed-pbm
    command: /opt/bitnami/kafka/bin/connect-standalone.sh /opt/bitnami/kafka/config/worker.properties /opt/bitnami/kafka/config/test_topic_sink.properties
    tty: true

  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "distributed_pbm"
      POSTGRES_USER: "msn"
      POSTGRES_PASSWORD: "psqlpass"
    volumes:
      - .:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - distributed-pbm

  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop2.7.4-java8
    container_name: namenode
    volumes:
      - /tmp/hdfs/namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=test
    env_file:
      - ./hadoop-hive.env
    ports:
      - "50070:50070"
    networks:
      net_pet:
        ipv4_address: 172.27.1.5

  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop2.7.4-java8
    container_name: datanode
    volumes:
      - /tmp/hdfs/datanode:/hadoop/dfs/data
      - ./bank:/bank
    env_file:
      - ./hadoop-hive.env
    environment:
      SERVICE_PRECONDITION: "namenode:50070"
    depends_on:
      - namenode
    ports:
      - "50075:50075"
    networks:
      net_pet:
        ipv4_address: 172.27.1.6

networks:
  net_pet:
    ipam:
      driver: default
      config:
        - subnet: 172.27.0.0/16
  distributed-pbm: